#pragma config(Motor,  port4,           test_motor,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           Left_Motor,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           Right_Motor,   tmotorVex393_MC29, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
{
motor[port4] = 127;
motor[Left_Motor] = 127;
motor[Right_Motor] = 127;
wait1Msec(2000);
}
}
